CREATE DATABASE election CHARACTER SET 'utf8';


CREATE TABLE Electeurs (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOM VARCHAR(20) NOT NULL,
POSTNOM VARCHAR(20) NOT NULL,
PRENOM VARCHAR(20) NOT NULL,
CODE INT(4) NOT NULL,
VOTE CHAR(3) DEFAULT 'NON' NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;



CREATE TABLE CP (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOM VARCHAR(20) NOT NULL,
POSTNOM VARCHAR(20) NOT NULL,
PRENOM VARCHAR(20) NOT NULL ,
IMAGE VARCHAR(255) NOT NULL,
VOIX INT(4) DEFAULT 0 NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


CREATE TABLE CPA (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOM VARCHAR(20) NOT NULL,
POSTNOM VARCHAR(20) NOT NULL,
PRENOM VARCHAR(20) NOT NULL ,
IMAGE VARCHAR(255) NOT NULL,
VOIX INT(4) DEFAULT 0 NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


CREATE TABLE Resultat_CP (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
CODE INT(4) NOT NULL,
ID_CP SMALLINT NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE Resultat_CPA (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
CODE INT(4) NOT NULL,
ID_CPA SMALLINT NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


INSERT INTO electeurs (NOM, POSTNOM, PRENOM, CODE)
VALUES ('KABONGO', 'BILONDA', 'KELLY', '1100'),
('KABONGO', 'MUKENA', 'DIEUDO', '2018'),
('MPOYI', 'MUKENA', 'NATHAN', '1998'),
('MUKENA', 'BAKINA', 'ARSENE', '1122'),
('MPUNGA', 'MUKENA', 'JOEL', '2248'),
('NTUMBA', 'MUKENA', 'SAMUEL', '2998'),
('KAZUMBA', 'KAMPIAMBA', 'BENI', '1198'),
('TSITA', 'POBA', 'JOE', '1908'),
('MBUYAMBA', 'KABUYI', 'MARDOCHEE', '1008'),
('MUTUMBIKA', 'MUKENA', 'CHRISTINE', '1458');





INSERT INTO cp (NOM, POSTNOM, PRENOM, IMAGE)
VALUES ('KALOMBO', 'MUKENA', 'BENJAMIN', 'images\\ben.jpg'),
('TSHIMAKINDA', 'MUKENA', 'JOSEPH', 'images\\joseph.jpg'),
('MUKADI', 'MUKENA', 'JOE', 'images\\joe.png');


INSERT INTO cpa (NOM, POSTNOM, PRENOM, IMAGE)
VALUES ('MUTUMBIKA', 'MUKENA', 'CHRISTINE', 'images\\christine.jpg'),
('MUANDA', 'MBADU', 'YORGHEN', 'images\\yorghen.jpg'),
('MUSHENDU', 'MUSHENDU', 'WILFRIED', 'images\\wilfried.png');

